/// Describes the full configuration options for a single benchmark run.
///
/// Note that not all of these can be configured from the command line, some are only available
/// if config is provided as a file.
pub struct RunConfig {
    /// A human-readable name of the run. This does not have to be unique (a separate unique
    /// ID will be assigned once the run has started).
    ///
    /// Example: `naive-algorithm`, `optimized-algorithm`, `test-1-core`, `test-8-core`, ...
    pub name: String,

    /// A command that will be used to execute individual benchmarks.
    ///
    /// If the command contains `@input`, this will be substituted with the path to the input
    /// file or the output of the input generator. If no `@input` is found, then the input is
    /// added as the last argument.
    ///
    /// The command can be given either as a single string or as a list, where the extra
    /// items represent the command arguments.
    ///
    /// Example: `my_program --arg1 @input`, `["python3", "my_script.py", "@input"]`, ...
    pub test_command: Vec<String>,

    /// The dataset that will be used to test the command. This can be a path to a
    /// folder, in which case each file in the folder is considered as one input. Alternatively,
    /// this can also be a command which will be executed and each line of its output is treated
    /// as one input item for the benchmarks. Note that the command is first executed until
    /// completion, and the benchmarking starts once all inputs are computed. In particular,
    /// it is not a good idea to store large amount of data inside input strings.
    ///
    /// Files from a folder are sorted lexicographically, but we keep the inputs generated by
    /// the input program in the order in which they were generated.
    ///
    /// Example: `/path/to/test/inputs`, `ls -1a src/*.rs`, `["python3", "my_data_generator.py"]`, ...
    pub input_data: Vec<String>,

    /// If specified, the output of each benchmark will be saved to the provided directory. The
    /// directory will be created if it does not exist. If not specified, the output is saved
    /// directly into the database.
    ///
    /// This is mostly used in cases where the output can be very large, and it isn't practical
    /// to have it in the database. Each file will be identified by its timestamp and job ID.
    ///
    /// Note that the last line of output is saved into the database regardless of this setting.
    ///
    /// Example: `/path/to/output/data`, ...
    pub raw_output: Option<String>,

    /// The maximum number of benchmarks that can be executed in parallel. Note that this does not
    /// limit the number of cores used by the individual benchmarks, just the number of benchmarks
    /// that we are allowed to run concurrently. Default is one (i.e. no parallelism).
    ///
    /// Example: If set to `8`, up to eight benchmarks can be executed simultaneously.
    pub parallelism: usize,

    /// If a benchmark is successful, it can be repeated multiple times to obtain more precise
    /// performance data. By default, a single repetition is used.
    ///
    /// Example: If set to `4`, each benchmark is repeated until four completed runs are observed.
    /// Runs that time out do not count towards this, but runs that fail for other reasons
    /// are considered as completed to avoid running tests with errors forever.
    pub repetitions: usize,

    /// The memory limit enforced for each child process, in `MiB` (mibibytes). Note that this is
    /// currently only supported on linux. On other operating systems, using memory limit produces
    /// a warning message but otherwise does nothing.
    ///
    /// Memory limit has a few caveats:
    ///  * Most programs nowadays need at least a few megabytes to start, especially
    ///    since we are also running `time` and `timeout`.
    ///  * The provided limit is the "soft" limit, hard limit is then set to 2x the soft limit.
    ///  * Memory errors are very unpredictable and hard to detect in the output, so even if memory
    ///    limit is applied, we generally don't differentiate between a generic "crash" and a
    ///    a memory limit issue. However, on linux, we collect the memory consumption of the
    ///    benchmarked process, so it is then possible to check which processes were
    ///    near the memory limit during post-processing.
    ///
    /// Example: If set to `1024`, each benchmark will have a memory limit of roughly
    /// one gigabyte.
    pub memory_limit: Option<u64>,

    /// The maximum allowed amount of time spent computing a single benchmark, in seconds. If
    /// not specified, the benchmarks will run with increasing timeout until some other error
    /// is triggered or until manually stopped.
    ///
    /// Example: If set to `60`, we will not further pursue benchmarks that were not completed
    /// in less than one minute.
    pub absolute_timeout: Option<usize>,
}

impl RunConfig {
    pub fn command_interpolation(&self, input: &str) -> Vec<String> {
        self.test_command
            .iter()
            .map(|it| it.replace("@input", input))
            .collect()
    }
}
